In [1]:
sentence = """Thomas Jefferson began building Monticello at the age of 26."""

In [2]:
import numpy as np

token_sequence =str.split(sentence)
vocab =sorted(set(token_sequence))
print('the sorted sequence or unique',vocab)
joined =','.join(vocab)
print(joined)
num_tokens =len(token_sequence)
vocab_size =len(vocab)
onehot_vectors =np.zeros((num_tokens,vocab_size),int)
for i ,word in enumerate(token_sequence):
  onehot_vectors[i, vocab.index(word)] =1
  print(f" sequence= {i}\n word={word}\n index_of_sorted_token={vocab.index(word)}\n")

print(onehot_vectors)



the sorted sequence or unique ['26.', 'Jefferson', 'Monticello', 'Thomas', 'age', 'at', 'began', 'building', 'of', 'the']
26.,Jefferson,Monticello,Thomas,age,at,began,building,of,the
 sequence= 0
 word=Thomas
 index_of_sorted_token=3

 sequence= 1
 word=Jefferson
 index_of_sorted_token=1

 sequence= 2
 word=began
 index_of_sorted_token=6

 sequence= 3
 word=building
 index_of_sorted_token=7

 sequence= 4
 word=Monticello
 index_of_sorted_token=2

 sequence= 5
 word=at
 index_of_sorted_token=5

 sequence= 6
 word=the
 index_of_sorted_token=9

 sequence= 7
 word=age
 index_of_sorted_token=4

 sequence= 8
 word=of
 index_of_sorted_token=8

 sequence= 9
 word=26.
 index_of_sorted_token=0

[[0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [3]:
import pandas as pd
df=pd.DataFrame(onehot_vectors,columns=vocab)
df[df == 0] =''
df

<ipython-input-3-e5ad6cb17e05>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[df == 0] =''


26. Jefferson Monticello Thomas age at began building of the
0                               1                             
1             1                                               
2                                            1                
3                                                     1       
4                        1                                    
5                                      1                      
6                                                            1
7                                   1                         
8                                                        1    
9   1

In [4]:
sentence_bow={}
for token in sentence.split():
  sentence_bow [token] =1

sorted(sentence_bow.items())

[('26.', 1),
 ('Jefferson', 1),
 ('Monticello', 1),
 ('Thomas', 1),
 ('age', 1),
 ('at', 1),
 ('began', 1),
 ('building', 1),
 ('of', 1),
 ('the', 1)]

In [5]:
df =pd.DataFrame(pd.Series(dict([(token,1) for token in sentence.split()])), columns=['sent']).T
df

Thomas  Jefferson  began  building  Monticello  at  the  age  of  26.
sent       1          1      1         1           1   1    1    1   1    1

In [6]:
sentences = """Thomas Jefferson began building Monticello at the\
age of 26.\n"""
sentences += """Construction was done mostly by local masons and\
 carpenters.\n"""
sentences += "He moved into the South Pavilion in 1770.\n"
sentences += """Turning Monticello into a neoclassical masterpiece\
was Jefferson's obsession."""

In [7]:
corpous={}
for i ,sent in enumerate(sentences.split('\n')):
  corpous['sent{}'.format(i)] = dict((tok,1) for tok in sent.split())
  df =pd.DataFrame.from_records(corpous).fillna(0).astype(int).T
  print(df[df.columns[:10]])

       26.  Jefferson  Monticello  Thomas  at  began  building  of  theage
sent0    1          1           1       1   1      1         1   1       1
       Thomas  Jefferson  began  building  Monticello  at  theage  of  26.  \
sent0       1          1      1         1           1   1       1   1    1   
sent1       0          0      0         0           0   0       0   0    0   

       Construction  
sent0             0  
sent1             1  
       Thomas  Jefferson  began  building  Monticello  at  theage  of  26.  \
sent0       1          1      1         1           1   1       1   1    1   
sent1       0          0      0         0           0   0       0   0    0   
sent2       0          0      0         0           0   0       0   0    0   

       Construction  
sent0             0  
sent1             1  
sent2             0  
       Thomas  Jefferson  began  building  Monticello  at  theage  of  26.  \
sent0       1          1      1         1           1   1       1   1 

In [8]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([2, 3, 4])
print(v1.dot(v2))

print((v1 * v2).sum())

print(sum([x1 * x2 for x1, x2 in zip(v1, v2)]))

20
20
20


In [9]:
v1.reshape(-1, 1).T @ v2.reshape(-1, 1)

array([[20]])

In [10]:
df=df.T #transpose
# sent[0].dot(sent[1])
print((df.sent0).dot(df.sent3))

[(k, v) for (k, v) in (df.sent0 & df.sent3).items() if v]

1


[('Monticello', 1)]

In [11]:
#Tokenize the Monticello sentence with a regular expression
import re
sentence = """Thomas Jefferson begans building Monticello at the age of 26."""
tokens = re.split(r'[-\s.,;\'!?]+', sentence)
print(tokens)

['Thomas', 'Jefferson', 'begans', 'building', 'Monticello', 'at', 'the', 'age', 'of', '26', '']


In [12]:
pattern = re.compile(r"([-/s,.!;\'\"?])+")
tokens =pattern.split(sentences)
tokens[-10:]

['s', 'on', 's', ' ob', 's', 'e', 's', 'ion', '.', '']

In [13]:
sentence = """Thomas Jefferson began building Monticello at the\
... age of 26."""
tokens = pattern.split(sentence)
[x for x in tokens if x and x not in '- \t\n.,;!?']


['Thoma', 's', ' Jeffer', 's', 'on began building Monticello at theage of 26']

In [14]:
pip install regex

In [15]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+|$[0-9.]+|\S+')
tokenizer.tokenize(sentence)

['Thomas',
 'Jefferson',
 'began',
 'building',
 'Monticello',
 'at',
 'theage',
 'of',
 '26',
 '.']

In [16]:
from nltk.tokenize import TreebankWordTokenizer
sentence = """Monticello wasn't designated as UNESCO World {Heritage}\
... Site until 1987."""
tokenizer =TreebankWordTokenizer()
tokens=tokenizer.tokenize(sentence,convert_parentheses=True)

In [17]:
!pip freeze | grep nltk

nltk==3.8.1


In [18]:
#Tokenize informal text from social networks such as Twitter and Facebook
from nltk.tokenize import casual_tokenize
message = """RT @TJMonticello Best day everrrrrrr at Monticello. Awesommmmmmeeeeeeee day :*)"""
print(casual_tokenize(message))
casual_tokenize(message ,reduce_len=True,strip_handles=True)


['RT', '@TJMonticello', 'Best', 'day', 'everrrrrrr', 'at', 'Monticello', '.', 'Awesommmmmmeeeeeeee', 'day', ':*)']


['RT',
 'Best',
 'day',
 'everrr',
 'at',
 'Monticello',
 '.',
 'Awesommmeee',
 'day',
 ':*)']

In [19]:
#s the n-gram tokenizer from nltk
from nltk.util import ngrams
list(ngrams(tokens,2))

[('Monticello', 'was'),
 ('was', "n't"),
 ("n't", 'designated'),
 ('designated', 'as'),
 ('as', 'UNESCO'),
 ('UNESCO', 'World'),
 ('World', '-LCB-'),
 ('-LCB-', 'Heritage'),
 ('Heritage', '-RCB-'),
 ('-RCB-', '...'),
 ('...', 'Site'),
 ('Site', 'until'),
 ('until', '1987'),
 ('1987', '.')]

In [21]:
stop_words = ['a', 'an', 'the', 'on', 'of', 'off', 'this', 'is']
tokens = ['the', 'house', 'is', 'on', 'fire']
token_without_stopwords =[x for x in tokens if x not in stop_words]
print(token_without_stopwords)

['house', 'fire']


In [25]:
import nltk
nltk.download('stopwords')
stop_words =nltk.corpus.stopwords.words('english')
len(stop_words)
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [33]:
from nltk.corpus import stopwords
print(stopwords.fileids())
hinglish = stopwords.words('bengali')
print(hinglish)
print(len(hinglish))

['arabic', 'azerbaijani', 'basque', 'bengali', 'catalan', 'chinese', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hebrew', 'hinglish', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'turkish']
['অতএব', 'অথচ', 'অথবা', 'অনুযায়ী', 'অনেক', 'অনেকে', 'অনেকেই', 'অন্তত', 'অন্য', 'অবধি', 'অবশ্য', 'অর্থাত', 'আই', 'আগামী', 'আগে', 'আগেই', 'আছে', 'আজ', 'আদ্যভাগে', 'আপনার', 'আপনি', 'আবার', 'আমরা', 'আমাকে', 'আমাদের', 'আমার', 'আমি', 'আর', 'আরও', 'ই', 'ইত্যাদি', 'ইহা', 'উচিত', 'উত্তর', 'উনি', 'উপর', 'উপরে', 'এ', 'এঁদের', 'এঁরা', 'এই', 'একই', 'একটি', 'একবার', 'একে', 'এক্', 'এখন', 'এখনও', 'এখানে', 'এখানেই', 'এটা', 'এটাই', 'এটি', 'এত', 'এতটাই', 'এতে', 'এদের', 'এব', 'এবং', 'এবার', 'এমন', 'এমনকী', 'এমনি', 'এর', 'এরা', 'এল', 'এস', 'এসে', 'ঐ', 'ও', 'ওঁদের', 'ওঁর', 'ওঁরা', 'ওই', 'ওকে', 'ওখানে', 'ওদের', 'ওর', 'ওরা', 'কখনও', 'কত', 'কবে', 'কমনে', 'কয়েক', 'কয়েকটি', 'করছে', 'করছেন', 'ক

In [41]:
#NLTK list of stop words
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS as sklearn_stop_words
print(len(sklearn_stop_words))
print(sklearn_stop_words)
print(len(set(stop_words).union(sklearn_stop_words)))
print(len(set(stop_words).intersection(sklearn_stop_words)))


318
frozenset({'five', 'formerly', 'she', 'alone', 'wherein', 'somehow', 'otherwise', 'hereupon', 'mine', 'be', 'latter', 'sixty', 'whenever', 'anything', 'thence', 'which', 'last', 'something', 'themselves', 'few', 'has', 'very', 'whose', 'although', 'further', 'between', 'at', 'whereas', 'enough', 'even', 'hasnt', 'with', 'nobody', 'namely', 'without', 'from', 'due', 'where', 'its', 'noone', 'it', 'your', 'after', 'many', 'detail', 'whom', 'fifteen', 'myself', 'anywhere', 'too', 'me', 'him', 'the', 'put', 'afterwards', 'hereafter', 'my', 'sometime', 'some', 'next', 'toward', 'cannot', 'whereafter', 'becomes', 'must', 'throughout', 'us', 'should', 'hundred', 'also', 'bill', 'cry', 'then', 'becoming', 'whole', 'because', 'less', 'yourselves', 'cant', 'he', 'ten', 'name', 'than', 'though', 'were', 'whereupon', 'you', 'am', 'either', 'seems', 'can', 'ourselves', 'as', 'thereupon', 'onto', 'back', 'much', 'however', 'wherever', 'neither', 'seemed', 'nevertheless', 'elsewhere', 'thereafter

In [46]:
def stem(phrase):
 return ' '.join([re.findall('^(.*ss|.*?)(s)?$', word)[0][0].strip("'") for word in phrase.lower().split()])

stem('powers')
stem("Doctor House's calls")

'doctor house call'

In [49]:
#e Porter and Snowball stemmers
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
' '.join(stemmer.stem(w).strip("'") for w in "dish washer's washed dishes".split())


'dish washer wash dish'

In [55]:
# The default part of speech is “n” for noun.
# “a” indicates the adjective part of speech
# nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('better',pos='a'))
print(lemmatizer.lemmatize('best',pos='n'))
lemmatizer.lemmatize('better',pos='n')

good
best


'better'

In [57]:
print(stemmer.stem('goodness')
)

good


In [70]:
pip install vaderSentiment

In [65]:
#SentimentIntensityAnalyzer.lexicon contains that dictionary of tokens and their scores that we talked about
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sa = SentimentIntensityAnalyzer()
print(len(sa.lexicon))
print([(tok, score) for tok, score in sa.lexicon.items() if " " in tok])
print(sa.polarity_scores(text="Python is very readable and it's great for NLP."))
print(sa.polarity_scores(text="Python is not a bad choice for most applications."))

7506
[("( '}{' )", 1.6), ("can't stand", -2.0), ('fed up', -1.8), ('screwed up', -1.5)]
{'neg': 0.0, 'neu': 0.661, 'pos': 0.339, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.737, 'pos': 0.263, 'compound': 0.431}


In [66]:
corpus = ["Absolutely perfect! Love it! :-) :-) :-)",
"Horrible! Completely useless. :(",
"It was OK. Some good and some bad things."]
for doc in corpus:
  scores = sa.polarity_scores(doc)
  print('{:+}: {}'.format(scores['compound'], doc))

+0.9428: Absolutely perfect! Love it! :-) :-) :-)
-0.8768: Horrible! Completely useless. :(
-0.1531: It was OK. Some good and some bad things.


In [79]:
!pip install nlpia
from nlpia.data.loaders import get_data
movies = get_data('hutto_movies')

ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

In [78]:
import pandas as pd
pd.set_option('display.width', 75)
from nltk.tokenize import casual_tokenize
bags_of_words = []
from collections import Counter
for text in movies.text:
 bags_of_words.append(Counter(casual_tokenize(text)))
df_bows = pd.DataFrame.from_records(bags_of_words)
df_bows = df_bows.fillna(0).astype(int)
df_bows.shape

NameError: name 'movies' is not defined